### ISSUE TITLE
Unstable WiFi connection

### ISSUE THREAD

**Issue by tipofthesowrd** [adonno/tagreader#44] opened 2020-09-29 15:52 UTC
The WiFi connection of the esp8266 to the network is unstable.
When connecting the pn532 module and after the setup of the module the WiFi connection and connection to the API stops & hangs often as evidenced by missing pings.

When the module is (physically) connected in HSU mode (or not setup) the connection is stable.

**Comment by gadgetshed** [comment] 2020-09-29 16:03
I can concur that the network connection is very flaky and it seems to drop off the network frequently.

**Comment by gadgetshed** [comment] 2020-09-29 19:14
I'm running a spi and i2c version next to each other and the i2c version is very stable in comparison so it's definitely the way to go.

As an aside the new schematic has the buzzer on D7 but the yaml is on D3 so I'm using D3 for wiring.

**Comment by tipofthesowrd** [comment] 2020-09-29 19:33
Where can I find the i2c version? Esphome didn't seem to have it in the
docs?

Op di 29 sep. 2020 21:14 schreef Steve Cooper <notifications@github.com>:

**Comment by jesserockz** [comment] 2020-09-29 19:52
@tipofthesowrd #45

**Comment by tipofthesowrd** [comment] 2020-09-30 16:35
I tried the i2c version, altough I see some improvement, there seem to be some other issues (see below).

As for the WiFi instability, I have the impression it is caused by the proximity of the pn532!!!
I'm using the printed STL files, when Wemos & the PN532 are close to each other the WiFi issues are there.
When I add jumper wires to seperate the boards without the printed housing the connection is stable.

As for the NDEF / I2C version: 

Tags written by the Home Assistant Android app are detected either as a NDEF and other times with a UUID.
Example from the same tag read in succession. This causes Home Assistant to detect it as two different tags!
Since the I2C version is not yet official I didn't want to open a seperate issue.

```
[18:28:00][D][ndef_tag_reader:057]: Tag Found!
[18:28:00][D][ndef_tag_reader:102]: No NDEF
[18:28:00][D][ndef_tag_reader:105]: Tag UID: 29-79-7B-9D
[18:28:00][D][text_sensor:015]: 'TagReader Tag': Sending state '29-79-7B-9D'
[18:28:01][D][text_sensor:015]: 'TagReader Tag': Sending state ''
[18:28:42][D][ndef_tag_reader:057]: Tag Found!
[18:28:42][D][ndef_tag_reader:065]: Tag has NDEF
[18:28:42][D][ndef_tag_reader:068]: Tag has 1 records
[18:28:42][D][text_sensor:015]: 'TagReader Tag': Sending state '8d2a73fc-fa4f-4968-8e3e-21e3b4034bbe'
```

**Comment by adonno** [comment] 2020-09-30 21:01
hey @tipofthesowrd what is the brand of this D1 you are using?  We seem to have issues with AZdelivery branded boards

**Comment by tipofthesowrd** [comment] 2020-10-01 04:19
@adonno  Nothing special, they are unbranded, ordered from a local seller for this projet. 

I was checking some more and found that when the boards are separated the ping only looses one packet every 10 seconds.
When placed in the housing, almost no ping comes through, except when the PN532 is not setup at boot. 

I was looking over the datasheet of the pn532 if there are some RF settings to tweak.

**Comment by jesserockz** [comment] 2020-10-01 04:50
I too have looked over the user guide for the board and could only find the RF on/off command, but nothing to specify power level.

**Comment by tipofthesowrd** [comment] 2020-10-01 05:12
No, I couldn't find anything either. However, there might be something in the way the library operates.

I noticed when reading a tag the ping gets better. I just found this:

```
  if (report) {
    char buf[32];
    format_uid(buf, nfcid, nfcid_length);
    ESP_LOGD(TAG, "Found new tag '%s'", buf);
  }

  this->turn_off_rf_();
```

After reading a tag the RF field is turned off, which might explain why I'm seeing a stable connection for a time after reading a card.

**Comment by mories76** [comment] 2020-10-01 10:12
Hi all,

It looks like I am experiencing the same wifi stability issues with a genuine lolin wemos d1 mini.
The tags read fine, HA is constantly connecting and disconnecting.
The PN532 is connected with a few centimeters of cable.

Later today I will solder some header and use jumper cables and see if the distance between the two have an effect.

**Comment by mories76** [comment] 2020-10-02 14:45
I have to withdraw my last comment ;-)
My wifi was having issues, I was too quick with my with my conclusion.

**Comment by tipofthesowrd** [comment] 2020-10-05 13:19
It might be with my specific type of D1 mini board: it is labeled DOITING. 
Reference: https://geekenargentina.wordpress.com/2019/10/08/esp8266-connectivity-troubleshooting/

When touching the antenna, the connection is immediately available. I'll see if I can desolder the tin can and check the capacitor.

**Comment by tobiasbayer** [comment] 2020-10-11 17:13
I can confirm it has something to do with the case or the position of the components inside it. My WiFi connectivity issues disappear as soon as I get the components out of the case and pull the ESP and the PN some (about 5) centimeters apart.

**Comment by tipofthesowrd** [comment] 2020-10-11 17:37
What's the marking on your D1 Mini case? I opened one case and removed the
capacitor as in the reference I linked above.

It's slightly better but still I'm getting serious and regular long
disconnects. I'm waiting for some more to arrive from AliExpress hoping
they're from another manufacturer

Op zo 11 okt. 2020 19:14 schreef Tobias Bayer <notifications@github.com>:

**Comment by tobiasbayer** [comment] 2020-10-11 17:48
![PXL_20201011_174644423](https://user-images.githubusercontent.com/313979/95685849-bddc6800-0bfa-11eb-9dca-f39671f7ec6d.jpg)

**Comment by adonno** [comment] 2020-10-11 22:02
@tobiasbayer I'd like you to test an Esphome Native I2C based binary  :  [tagreader-i2c.zip](https://github.com/adonno/tagreader/files/5362204/tagreader-i2c.zip)
same goes for everyone else having issues. 


**You will have to change the wireing for I2C**
```
D1 --> SCL
D2 --> SDA
```
(please also use GND and VCC from the I2C side)
And do change the Jumper switches on the PN532 for I2C ( 1 Up / 2 Down)

I've been testing for several days and I must admit it works almost flawless (disconnected sometimes due to me moving it around)
![image](https://user-images.githubusercontent.com/13216947/95691224-de69e980-0c1d-11eb-91bf-9f1307f968aa.png)

**Comment by tipofthesowrd** [comment] 2020-10-12 06:47
@adonno I just flashed this verison. I'll report back about my findings.  
What's specific about this binary? Anything different the pull request by @jesserockz ?

**Comment by jesserockz** [comment] 2020-10-12 06:50
It's a binary from along the track of #52.
#52 has tag writing as well, but that binary only has reading

**Comment by tobiasbayer** [comment] 2020-10-12 11:49
I flashed the I2C version and did the rewiring. WiFi seems to be pretty stable now.

**Comment by tipofthesowrd** [comment] 2020-10-12 18:34
Same here! This specific binary works great for me as well.

Op ma 12 okt. 2020 13:50 schreef Tobias Bayer <notifications@github.com>:

**Comment by dojf** [comment] 2020-10-13 17:44
I flashed the I2C version on a extra ESP8266 D1 Mini and extra PN532 . The difference is big as can be seen in the comparison  below (same timespan). Great work, thank you!

![Tagreader compare](https://user-images.githubusercontent.com/36510293/95895969-d16b0880-0d8b-11eb-9818-ae93a262623a.png)

Also a very pleasant surprise that the (programmeble) long tags work in this version, thanks!

**Comment by slemiere** [comment] 2020-10-16 20:33
Same effect for me, I was getting disconnects every few minutes and now with the I2C build it's super stable. D1 mini is coming from az-delivery

**Comment by dartfrogdk** [comment] 2020-11-04 12:38
this file seem very stable

**Closed** 2020-11-05 20:14 UTC

**Comment by apeeters** [comment] 2020-11-24 11:16
> I noticed when reading a tag the ping gets better. I just found this:
> ```
>   this->turn_off_rf_();
> ```
> 
> After reading a tag the RF field is turned off, which might explain why I'm seeing a stable connection for a time after reading a card.

I was the one who added that line in an attempt to get a more stable WiFi connection. I now moved to the pn532_i2c version which is WAY more stable, great work!
